//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionItem
    {
        public ActionItem()
        {
            this.DelFlag = true;
            this.UserInfo = new HashSet<UserInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public int ID { get; set; }
        public string ActionItemName { get; set; }
        public string ActionItemNo { get; set; }
        public string Sort { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime RegTime { get; set; }
        public System.DateTime ModfiedOn { get; set; }
        public int ActionInfoID { get; set; }
    
        public virtual ActionInfo ActionInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
