//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.DelFlag = true;
            this.IsMenu = false;
            this.ParentId = -1;
            this.RoleInfo = new HashSet<RoleInfo>();
            this.UserInfo = new HashSet<UserInfo>();
            this.ActionItem = new HashSet<ActionItem>();
        }
    
        public int ID { get; set; }
        public string ActionName { get; set; }
        public string ParentName { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime RegTime { get; set; }
        public System.DateTime ModfiedOn { get; set; }
        public string Url { get; set; }
        public string HttpMethd { get; set; }
        public bool IsMenu { get; set; }
        public string MenuIcon { get; set; }
        public string Sort { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual ICollection<ActionItem> ActionItem { get; set; }
    }
}
