//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInfo
    {
        public AddressInfo()
        {
            this.IsDefault = false;
            this.DelFlag = true;
        }
    
        public int ID { get; set; }
        public string Consignee { get; set; }
        public string Telphone { get; set; }
        public string DetailedAddress { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public int UserInfoID { get; set; }
        public string PostCode { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
