//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartInfo
    {
        public CartInfo()
        {
            this.GoodsNum = 1;
            this.GoodsPrice = 0m;
            this.DelFlag = true;
        }
    
        public int ID { get; set; }
        public Nullable<int> GoodsNum { get; set; }
        public Nullable<decimal> GoodsPrice { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public int UserInfoID { get; set; }
        public int GoodsInfoID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual GoodsInfo GoodsInfo { get; set; }
    }
}
