//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
        public DbSet<OrderInfo> OrderInfo { get; set; }
        public DbSet<GoodsInfo> GoodsInfo { get; set; }
        public DbSet<GoodsType> GoodsType { get; set; }
        public DbSet<LinksInfo> LinksInfo { get; set; }
        public DbSet<FocusPicture> FocusPicture { get; set; }
        public DbSet<Freight> Freight { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<WFTemp> WFTemp { get; set; }
        public DbSet<WFInstance> WFInstance { get; set; }
        public DbSet<FileInfo> FileInfo { get; set; }
        public DbSet<WFStep> WFStep { get; set; }
        public DbSet<AddressInfo> AddressInfo { get; set; }
        public DbSet<LoginLog> LoginLog { get; set; }
        public DbSet<CartInfo> CartInfo { get; set; }
        public DbSet<OrderDetailInfo> OrderDetailInfo { get; set; }
        public DbSet<Deals> Deals { get; set; }
        public DbSet<Dept> Dept { get; set; }
        public DbSet<SysLog> SysLog { get; set; }
        public DbSet<ActionItem> ActionItem { get; set; }
        public DbSet<Comment> Comment { get; set; }
    }
}
