//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public Deals()
        {
            this.pay_order_amount = 0m;
            this.DelFlag = true;
        }
    
        public int ID { get; set; }
        public string pay_order_no { get; set; }
        public Nullable<decimal> pay_order_amount { get; set; }
        public string pay_user_name { get; set; }
        public int PaymentID { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
