//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInfo
    {
        public FileInfo()
        {
            this.DelFlag = true;
            this.WFInstance = new HashSet<WFInstance>();
        }
    
        public int ID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
    
        public virtual ICollection<WFInstance> WFInstance { get; set; }
    }
}
