//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo
    {
        public GoodsInfo()
        {
            this.GoodsPrice = 0m;
            this.DelFlag = true;
            this.Status = 0;
            this.Point = 0;
            this.OrderDetailInfo = new HashSet<OrderDetailInfo>();
            this.CartInfo = new HashSet<CartInfo>();
            this.Comment = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> GoodsPrice { get; set; }
        public string GoodsRemark { get; set; }
        public Nullable<int> GoodsNum { get; set; }
        public string ImageMenu { get; set; }
        public string GoodsAddress { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public int UserInfoID { get; set; }
        public int GoodsTypeID { get; set; }
        public Nullable<int> Status { get; set; }
        public int Point { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual GoodsType GoodsType { get; set; }
        public virtual ICollection<OrderDetailInfo> OrderDetailInfo { get; set; }
        public virtual ICollection<CartInfo> CartInfo { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
