//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public OrderInfo()
        {
            this.Money = 0m;
            this.DelFlag = true;
            this.OrderDetailInfo = new HashSet<OrderDetailInfo>();
        }
    
        public int ID { get; set; }
        public string OrderName { get; set; }
        public string Content { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<System.DateTime> SuccessTime { get; set; }
        public int UserInfoID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<OrderDetailInfo> OrderDetailInfo { get; set; }
    }
}
