//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UserPwd = "123456";
            this.DelFlag = true;
            this.IsSys = false;
            this.State = true;
            this.Amount = 0m;
            this.RoleInfo = new HashSet<RoleInfo>();
            this.OrderInfo = new HashSet<OrderInfo>();
            this.GoodsInfo = new HashSet<GoodsInfo>();
            this.AddressInfo = new HashSet<AddressInfo>();
            this.CartInfo = new HashSet<CartInfo>();
            this.ActionInfo = new HashSet<ActionInfo>();
            this.ActionItem = new HashSet<ActionItem>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string salt { get; set; }
        public string UserPwd { get; set; }
        public string Avatar { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public Nullable<bool> IsSys { get; set; }
        public int DeptID { get; set; }
        public Nullable<bool> State { get; set; }
        public string Moblie { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Telphone { get; set; }
        public string area { get; set; }
        public string Address { get; set; }
        public string qq { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Point { get; set; }
        public string Description { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
        public virtual ICollection<GoodsInfo> GoodsInfo { get; set; }
        public virtual ICollection<AddressInfo> AddressInfo { get; set; }
        public virtual ICollection<CartInfo> CartInfo { get; set; }
        public virtual Dept Dept { get; set; }
        public virtual ICollection<ActionInfo> ActionInfo { get; set; }
        public virtual ICollection<ActionItem> ActionItem { get; set; }
    }
}
