//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInstance
    {
        public WFInstance()
        {
            this.DelFlag = true;
            this.FileInfo = new HashSet<FileInfo>();
            this.WFStep = new HashSet<WFStep>();
        }
    
        public int ID { get; set; }
        public string InstanceName { get; set; }
        public int StartBy { get; set; }
        public System.DateTime StartTime { get; set; }
        public short Level { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public int WFTempID { get; set; }
        public System.Guid WFInstanceId { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ICollection<FileInfo> FileInfo { get; set; }
        public virtual WFTemp WFTemp { get; set; }
        public virtual ICollection<WFStep> WFStep { get; set; }
    }
}
