//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFStep
    {
        public int ID { get; set; }
        public string StepName { get; set; }
        public int ProcessBy { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string ProcessResult { get; set; }
        public string ProcessComment { get; set; }
        public Nullable<short> StepStatus { get; set; }
        public Nullable<bool> IsStartStep { get; set; }
        public Nullable<bool> IsEndStep { get; set; }
        public Nullable<int> ParentStepId { get; set; }
        public int WFInstanceID { get; set; }
    
        public virtual WFInstance WFInstance { get; set; }
    }
}
